version: "3.9"

networks:
  app-network:
    driver: bridge
  
services:
  database:
    build: ./database
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - app-network
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  website:
    build: ./website
    restart: always
    ports:
      - ${FLASK_PORT}:8080
    networks:
      - app-network
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - FLASK_HOST=${FLASK_HOST}
      - FLASK_PORT=${FLASK_PORT}
    depends_on:
      - database